### ISSUE TITLE
Pasword setup during sign up UX issues

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#420]
When first signing up, there is no password policy visible for the user (1).
![image](https://github.com/eyra/mono/assets/88683839/5c1c7db5-612b-42ee-93cc-59ea28d3d837)
But when the password is not according to the policy, the policy is displayed, but the length is a placeholder (2).
![image](https://github.com/eyra/mono/assets/88683839/cf0a6c38-6edb-4e84-a587-529847db648b)

**Comment by emielvdveen** [comment]
Fixed
