### ISSUE TITLE
Graceful handling of application when database connection is (temporary) lost

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#441]
When the application - for some reason - loses it's database connection, it should not crash but it should show a friendly error message to the users. I'm not sure what happens currently if such an event would happen.

When the database comes back online, the application should be able to continue, although certain actions may have failed and need to be retried by the user.

**Comment by emielvdveen** [comment]
@TjerkNan Can you create a `research todo `on Bascecamp for this and close this issue on github for now?

**Comment by AdrienneMendrik** [comment]
Added to basecamp
