### ISSUE TITLE
Force language to Dutch for LISS data donation studies

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#535]
Make sure data donation studies that run within the LISS panel are in Dutch.

**Comment by emielvdveen** [comment]
@AdrienneMendrik fix available in [2024-01-03_391](https://github.com/eyra/mono/releases/tag/next_2024-01-03_391)

**Comment by emielvdveen** [comment]
Note: the language is not forced in preview mode (Researchers)

**Comment by AdrienneMendrik** [comment]
Tested by Bella, works well.
