### ISSUE TITLE
Delete project (long view)

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#551]
Steps followed:
- Go to projects
- Click the dots
- Click trash can to delete project

Expected:
Small confirmation box

Instead:
Box stretched vertically over the screen

See screenshot and movie below:

![Screenshot 2024-01-11 at 13 16 09](https://github.com/eyra/mono/assets/79082794/fec3ac41-c046-4f7d-afde-927e022ca1e2)

https://github.com/eyra/mono/assets/79082794/81a6be1b-ddce-41db-b1cb-c3b15efc1813

**Comment by TjerkNan** [comment]
Fixed!
