### ISSUE TITLE
Sign up flow (Access Denied error)

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#552]
Tested by: Neo

Steps followed:

- Sign up
- Fill out Email field
- Fill out Password field
- Check e-mail
- Click on link in e-mail
- Sign in

Expected:
To be signed in on the Next platform

Instead: 
Access denied

(sign in tried again, again access denied error)

![Scherm_afbeelding 2024-01-11 om 13 05 28](https://github.com/eyra/mono/assets/79082794/f8be5618-2a3b-4fd1-bc8a-8dfb0cddf88d)

**Comment by AdrienneMendrik** [comment]
@emielvdveen assign researcher rights for access.

**Comment by emielvdveen** [comment]
Fixed
