### ISSUE TITLE
Add email address to my profile

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#575]
View e-mail address in "My Profile", such that people know with which e-mail address they are signed in. They cannot change this e-mail address for now.

**Comment by neocheungdesigneyra** [comment]
Design: https://www.figma.com/file/UxitjYs2RK9cVsl2XS9jaQ/Next?type=design&node-id=1039-5969&mode=design&t=mk8RveVwXkkyyVxb-11

**Comment by emielvdveen** [comment]
<img width="697" alt="Screenshot 2024-01-31 at 17 47 07" src="https://github.com/eyra/mono/assets/262448/a0a3ba52-3117-4748-8113-198d12438970">

**Comment by AdrienneMendrik** [comment]
Looks good.
