### ISSUE TITLE
Project item deleted without confirmation

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#577]
**Describe the bug**
When clicking on the delete button of an item, the item is immediately deleted.
It is possible for people to accidentally delete an issue, which could have severe consequences.

**To Reproduce**
1. Go to Projects
2. Click on a project
3. Add item 
4. Click on ... on the item
5. Click on the trash can 

**Expected behavior**
A message asking for confirmation whether I really want to delete this item.

**Screenshots**
https://github.com/eyra/mono/assets/88683839/085d8168-de0d-4a41-b96a-c4db313760f2

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser Any

**Comment by neocheungdesigneyra** [comment]
Design toegevoegd in design system: 
![image](https://github.com/eyra/mono/assets/156786926/4cf8a66e-6a1a-4fc6-ac3a-0572d2caab83)

Link: https://www.figma.com/file/RXKuvMFGz3Eln5MNPJ1q6a/Design-system?type=design&node-id=1-444&mode=design&t=wjgZkleBpEsrmWPe-11

**Comment by AdrienneMendrik** [comment]
Will be solved in a different way.
