### ISSUE TITLE
Make button for next step more visible

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#578]
**Is your feature request related to a problem? Please describe.**
The data donation workflow has two steps: 

1. Settings
2. Workflow

This is visible at the top like this. 
![Screenshot 2024-01-19 at 17 03 37](https://github.com/eyra/mono/assets/88683839/cc4d6060-e530-4be6-8b1c-31a5e7d6577b)

At the bottom there is a "Workflow" button to go to the second step in the workflow.
![image](https://github.com/eyra/mono/assets/88683839/0fb2b23e-2e1c-4916-81d7-f2a082f9bf99)

**Describe the solution you'd like**
Button at the bottom is not well visible, I would like it to be more clear, maybe replicate the top level bar for the workflow also at the bottom.

**Describe alternatives you've considered**
Make the existing "Workflow >" text  larger, to make it better visible.

**Comment by AdrienneMendrik** [comment]
Won't fix.
