### ISSUE TITLE
Text fields emptied

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#579]
**Describe the bug**
Within the data donation workflow  a researcher has to enter text (some optional) for the following fields

1. Information page
2. Consent form
3. Helpdesk page

Text stored in these rich text fields is lost if you click 'skip' and then go back.

**To Reproduce**
1. Within a project add a data donation item
2. Click on new item 
3. Go to any text field
4. enter text

Method one:
5. Click on skip
6. click on show
7. The text is gone

https://github.com/eyra/mono/assets/88683839/deb6f308-f28d-4baf-8875-2a463e80f540

**Expected behavior**
Text does not disappear. People may accidentally click on the skip button and loose their text.

**Screenshots**
See above for movie.

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser: any

**Comment by AdrienneMendrik** [comment]
Maybe we can address this issue, by prompting a popup, when you have text in your field and switch to skip. Are you sure you would like to skip this page? Your text will be deleted, or something like that. 

Something similar to when you want to delete a project.

**Comment by mellelieuwes** [comment]
@TjerkNan Implemented suggestion by @AdrienneMendrik :

> Maybe we can address this issue, by prompting a popup, when you have text in your field and switch to skip. Are you sure you would like to skip this page? Your text will be deleted, or something like that.
> 
> Something similar to when you want to delete a project.

**Comment by TjerkNan** [comment]
Tested all fields, shows popup when empty.
