### ISSUE TITLE
No confirmation when disconnecting panel

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#580]
**Describe the bug**
Because the pannel connection disconnect button does not ask for confirmation, the pannel connection is immediately disconnected. As this button can be easily clicked by accident, there is an elevated risk. This may impact running studies.

A study that is published is also affected.

**To Reproduce**
1. Select a data donation item within a workflow or create one
3. Create a Panel connection, any one will do
4. Press the disconnect button 
5. The panel is immediately disconnected

Other method with related outcome:
1. Create a panel connection
2. Edit the panel connection
3. Select a different connection type
4. The other connection type is immediately selected

**Expected behavior**
I would expect a confirmation dialog alerting the user of the implications.

**Screenshots**

https://github.com/eyra/mono/assets/88683839/faee34fe-4a30-48b4-9b4a-5ecdb2fe89ba

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser Any

**Comment by AdrienneMendrik** [comment]
Not going to be picked up, might reappear later.
