### ISSUE TITLE
S3 storage configuration sometimes empty

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#581]
**Describe the bug**
If you have S3 storage configured but accidentally click on Azure Blob storage or another option, but then click on S3 again, all settings for S3 storage seem to be gone. 

However, if you click on projects at the left, and navigate back to the data donation item, and click on storage, you'll notice that the settings were not gone and are still there.

**To Reproduce**
1. Add S3 storage to a data donation item
2. Fill out all the required fields (can be just test data)
3. Click on Azure Blob 
4. Click back on S3 Storage
5. All fields are empty. 
6. Click on cancel
7. Click on edit
10. Select S3 and notice that the fields contain settings.

**Expected behavior**
When clicking from Azure Blob back to S3 storage, I expect the S3 fields still to contain settings. 

**Screenshots**
https://github.com/eyra/mono/assets/88683839/a558efab-dfe2-420a-8a17-15229638501e

**Desktop (please complete the following information):**
 - Browser Any

**Comment by AdrienneMendrik** [comment]
Not going to be picked up, might reappear later.
