### ISSUE TITLE
Data source selection in workflow

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#582]
**Describe the bug**
When selecting a data source for the Data donation workflow, you have to very precisely click on the small arrow at the right of the text field. 

I also can't just enter the name of a data source, it seems that you have to select it from the list of options. 

**To Reproduce**
1. create a new data donation workflow
2. In the 'Donate' block click on the data source field to the left of the arrow
3. The field does not respond. 

**Expected behavior**
1. Clicking anywhere in the field would result in showing the pulldown list 
2. Manually typing the name of the item would select the right item, with the correct capitalisation

**Screenshots**

https://github.com/eyra/mono/assets/88683839/81f7ac0f-069a-4394-8004-b3b276d3e8a8

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Any

**Comment by emielvdveen** [comment]
I tested it today and typing seems to work again. The dropdown is for the ones we have logos for. You can type in any custom data source but this wont result in a logo being displayed for the participant. Arguably not the best UI but ok for now.

**Comment by TjerkNan** [comment]
I'm now able to select amongst many social media sites
