### ISSUE TITLE
Password nr of characters error

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#585]
**Describe the bug**
When a password has too little characters the text of the error shows %{count} instead of the minimum number of characters. Example: should be at least %{count} character(s).

**To Reproduce**
1. Go to sign up
2. Type a short password, for example one character
3. Click "Sign up"

**Expected behavior**
An error with the minimum number of characters allowed for a password.

**Screenshots**
![count-error](https://github.com/eyra/mono/assets/79082794/745dc25f-a86b-4fd6-803c-62cb22af01f7)

**Comment by emielvdveen** [comment]
<img width="446" alt="Screenshot 2024-01-23 at 13 44 31" src="https://github.com/eyra/mono/assets/262448/e7b726fe-f968-4327-ab2d-02999c6d5b14">

**Comment by TjerkNan** [comment]
Minor cosmetic issue reported in #589 but for now I consider that non-blocking.
