### ISSUE TITLE
Errors new password

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#586]
**Describe the bug**
Errors for password requirements are printed over confirm password title.

**To Reproduce**
1. Go to sign in
2. Click on change password (reset password)
3. Fill out your email address
4. Click on the link in the email to provide a new password
5. Type a short 2 character password with no digit or upper case characters
6. Click reset / change

**Expected behavior**
Show error that is clearly visible.

**Screenshots**
![Errors-newpassword](https://github.com/eyra/mono/assets/79082794/4e8dd5f6-e841-4224-ae07-bcea39bd78b2)

**Comment by emielvdveen** [comment]
<img width="507" alt="Screenshot 2024-01-23 at 14 16 35" src="https://github.com/eyra/mono/assets/262448/e443e7aa-62c4-480b-9f1c-2902e7862076">

**Comment by TjerkNan** [comment]
Unable to reproduce.
