### ISSUE TITLE
Sign in field emptied

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#593]
**Describe the bug**
At the sign in page, when I fill out the Email field (both with copy - paste and while typing) the Email field is emptied before I get a chance to fill in my password and sign in.

**To Reproduce**
1. Go to sign in
2. Fill out the Email field
3. Wait or start typing password

**Expected behavior**
The email field not to be emptied until I click "Sign in".

**Screenshots**
Link to the movie: https://drive.google.com/file/d/1kQIFdpJtAEg5o7Pv63qE6vB3sHvxGjFd/view?usp=drive_link

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome, safari

**Comment by emielvdveen** [comment]
@AdrienneMendrik This should be fixed on production, can you test it?
