### ISSUE TITLE
Cms refresh jump to top

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#594]
**Describe the bug**
When scrolling down in the data donation researcher CMS, after a while the page jumps to the top again.

**To Reproduce**
1. Go to projects
2. Click on a project and data donation item
3. Scroll down in the cms settings page
4. Wait for about 30 seconds
5. See error

**Note:** Happens sometimes, not always, not sure under what circumstances it happens. Only on production, not on dev environment.

**Expected behavior**
The CMS page to remain at the location where I am working.

**Screenshots**
Movie:
https://github.com/eyra/mono/assets/79082794/86652dfa-e166-4c2d-939f-9aae56c7c9a4

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome

**Comment by emielvdveen** [comment]
@AdrienneMendrik issue is fixed on production, can you test it?

**Comment by AdrienneMendrik** [comment]
Tested, issue fixed.
