### ISSUE TITLE
Data storage on Next

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#611]
**Is your feature request related to a problem? Please describe.**
There is currently no way to store data on the Next platform.

**Describe the solution you'd like**
Add an option to select the Next platform as a storage type in addition to the other available options.

**Additional context**
Screenshot of the Next platform where it might be nice to add the option:

![Screenshot 2024-02-06 at 17 22 20](https://github.com/eyra/mono/assets/79082794/2bfa79f6-5547-4503-8918-43046393df56)

**Comment by neocheungdesigneyra** [comment]
Design
https://www.figma.com/file/UxitjYs2RK9cVsl2XS9jaQ/Next?type=design&node-id=425-16393&mode=design&t=iNRRxbKN8VfltRBo-11

**Comment by emielvdveen** [comment]
<img width="1876" alt="Screenshot 2024-02-12 = at 14 23 51" src="https://github.com/eyra/mono/assets/262448/426d12b9-f901-46fd-bc20-1c29b2599140">
