### ISSUE TITLE
Download donated data

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#612]
**Is your feature request related to a problem? Please describe.**
If data is saved on the Next platform, I would like to have the option to download the data.

**Describe the solution you'd like**
Once the option to save the data on the Next platform is selected (https://github.com/eyra/mono/issues/611), add a button to download the data.

**Comment by neocheungdesigneyra** [comment]
Design download button in card:
https://www.figma.com/file/UxitjYs2RK9cVsl2XS9jaQ/Next?type=design&node-id=425-16393&mode=design&t=iNRRxbKN8VfltRBo-11
