### ISSUE TITLE
Account activation email link immediately invalidated 

### ISSUE THREAD

**Issue by kasperwelbers** [eyra/mono#615]
**Describe the bug**
When I clicked on the account creation confirmation link in the email I received from Next, the link was already invalidated, and I was prompted to re-send the email to try again. However, the account was actually created the first time. The user is thus send on a wild goose chase. 

This could be because some mail clients (at least Outlook) have a safe link feature. When you click a link, a HEAD request is send ahead of you, which can notoriously mess up activation emails / magic links. When setting up magic links for an application I also encountered [this issue](https://serverfault.com/questions/1120740/outlooks-safelinks-send-get-requests-why-isnt-this-a-bigger-issue) where Outlook sometimes sends a GET request, and this can happen before the user clicks the link. This also makes it a potential security risk, because I could create an account on someone else's email address, and the account could be activated without the person's approval. 

**To Reproduce**
You'll need an account on a mail client that shows this behavior (like VU Outlook). Make a new account, and click on the link in the confirmation mail.

**Expected behavior**
A message that my account has been created, or at least not an error message

**Current behavior**
See this message and an input field for entering my mail address:

"Your account activation link is invalid or it has expired. Enter your email address and click resend to receive a new account activation link."

**Desktop (please complete the following information):**
 - OS: Linux / Ubuntu
 - Browser: Chrome
 - Version: 119.0.6045.159

**Additional context**

**Comment by emielvdveen** [comment]
@AdrienneMendrik I added styling and copy (eyra-account.po) for the activation failed scenario. The page was still un-styled.

<img width="1890" alt="Screenshot 2024-02-28 at 18 49 35" src="https://github.com/eyra/mono/assets/262448/e0a1e1af-19fd-4bae-b76b-e6589da13454">

**Comment by TjerkNan** [comment]
- Tested with web-based outlook account
- Tested with macos native mail client
- Presssed on button 'load remote content' 

Used multiple accounts, could not reproduce the issue.

**Comment by kasperwelbers** [comment]
> * Tested with web-based outlook account
> * Tested with macos native mail client
> * Presssed on button 'load remote content'
> 
> Used multiple accounts, could not reproduce the issue.

Have you also verified that these mail clients have safelinks (or similar link scanning) enabled?  

In my case I can only produce the issue on my VU outlook (which has some enterprise level phishing protection). Though I can't reproduce it on Next since I already have an account.
