### ISSUE TITLE
Feldspar app_viewer has too much padding on mobile

### ISSUE THREAD

**Issue by kasperwelbers** [eyra/mono#616]
**Describe the bug**
When running a Feldspar app in Next, the left padding is too big for mobile devices. (sufficiently 'too big' that it harms usability). 

[faux pull request] A solution would be to change "pl-20" to "pl-4 md:pl-20" in `core/systems/feldspar/app_view.ex`. This aligns with the breakpoint where Next drops the sidepadding.

**To Reproduce**
1. Open a Feldspar app in Next
2. squeeze the screen below tailwind's md width (768 px) 

**Expected behavior**
The app_viewer should give Feldspar enough space. The left and right padding should align.

**Comment by emielvdveen** [comment]
<img width="448" alt="Screenshot 2024-02-28 at 11 48 58" src="https://github.com/eyra/mono/assets/262448/477a2293-7c16-4462-8a7b-09b9ae4af2cf">

**Comment by kasperwelbers** [comment]
Cool, thanks!

**Comment by TjerkNan** [comment]
- Unable to reproduce the problem, followed the donation flow and GUI was usable, no issues.
