### ISSUE TITLE
Donated data not stored on internal S3 storage

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#619]
**Describe the bug**
After a donation with either Apple or Samsung worklfow completes, data is not stored in S3.

**To Reproduce**
Follow these instructions exactly
https://3.basecamp.com/5734045/buckets/36045960/todos/7083945948

**Expected behavior**
Data being stored in S3 according to specification in same URL

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macos
 - Browser safari/firefox

**Comment by emielvdveen** [comment]
AWS_S3_BUCKET staat voor dev omgeving p "eyra-prod". Ik heb dit aangepast en service herstart en nu werkt het als het goed is.

**Comment by TjerkNan** [comment]
```
$ aws --profile eyra-dev s3 ls eyra-dev/storage_dev/assigment=72/
tjerknan@bastion-host ~/devops/ansible (master)
```
Er worden folders aangemaakt maar er lijkt iets niet goed te gaan nog steeds helaas

**Comment by TjerkNan** [comment]
Klopt werkt nu goed.
``` 
ls eyra-dev/storage_dev/
                           PRE assignment=72/
                           PRE assignment=74/
```
```
$ aws --profile eyra-dev s3 ls eyra-dev/storage_dev/assignment=75/
2024-02-14 23:07:22     106287 participant=12341234_source=Apple_1707948430480.json
```
