### ISSUE TITLE
participant={id} value can be manipulated to likely break app 

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#620]
**Describe the bug**
The id parameter can be whatever you supply as arguments, such as path traversal or long nonsensical strings. 
This is then stored in S3 and it may not be a direct security vulnerability, but the path traversal example will cause problems when downloading those files to a local computer and the XSS example also breaks the app probably.

```
$ aws --profile eyra-dev s3 ls eyra-dev/storage_dev/assignment=75/
                           PRE participant=<script>alert(‘XSS’)</
2024-02-14 23:11:39     106287 participant=..\..\..\..\..\_source=Apple_1707948687610.json
2024-02-14 23:07:22     106287 participant=12341234_source=Apple_1707948430480.json
2024-02-14 23:09:26     106287 participant=dancingqueennnnnwefwefaefawefawefawefawefawefawefawefawefawefawefawefawefawefawefaefawefwefwiefhwiuefhwuigfyiwuefuywegfuywgeufyweuyfweuyfwuyefuywegfuywegfuywegfuywgefuyweufyweufywueyfwuyefguwyegfuwyegfuwygfuwyefuwyefguwyegfuywefguwyefguwyefguwyefguwyefguywefguwyfuywefuywefuywefuywefuywefuywefgweuyfw_source=Apple_1707948553202.json

$ aws --profile eyra-dev s3 ls "eyra-dev/storage_dev/assignment=75/participant=<script>alert(‘XSS’)</"
2024-02-14 23:18:35     106287 script>_source=Apple_1707949103225.json

```
**To Reproduce**
1. Generate a panel URL for a new donation workflow like this: 
https://next.dev.eyra.co/assignment/75/participate?participant={id}&language=nl
2. mess with the {id} parameter in whatever evil way you like.

**Expected behavior**
One or more options like:
1. special characters are forbidden or replaced with safe chars
2. id length is truncated to x chars (to be decided)

**Screenshots**
See output above.

**Desktop (please complete the following information):**
Not relevant

**Comment by emielvdveen** [comment]
@rowdyvl kan je deze inplannen om op te pakken?

**Comment by emielvdveen** [comment]
@TjerkNan if I open that last link I get this:

<img width="1318" alt="Screenshot 2024-03-05 at 14 43 07" src="https://github.com/eyra/mono/assets/262448/d45b2a60-2777-4a00-b3bd-1a7a3bbf27fb">

How did you get past this?

**Comment by TjerkNan** [comment]
I accessed the page while logged in with my next.dev.eyra.co credentials and that's why it works.
When I use a different browser I can't reproduce it. 
It may be good-enough for now or for a long time, however, filenames stored in S3 are still not sanitized.
Maybe the risk is now mitigated enough to give this issue a pass.

**Comment by emielvdveen** [comment]
@TjerkNan nice find, will fix it

**Comment by TjerkNan** [comment]
Logged-in with eyra account on dev machine, the url can't be messed with anymore, as with <script> style tags. (Access denied)
Valid characters provide access as it should.
