### ISSUE TITLE
When donating, clicking 'no' it should not show the same 'thank you' 

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#621]
**Describe the bug**
I got a heart attack when I clicked 'no' and the app showed a big 'thank you' screen, implying - at first - as if I still donated.

**To Reproduce**
1. select a file for donation
2. instead of pressing 'donate', press 'no'.

**Expected behavior**
A clear message that the data was *not* donated, not the 'green' "Thank You!".

**Screenshots**

https://github.com/eyra/mono/assets/88683839/d6261778-9c4f-4b59-8a0f-e3c563735e54

**Desktop (please complete the following information):**
 - OS: macos
 - browser: any

**Comment by AdrienneMendrik** [comment]
I changed the copy to: Done instead of Thank you and in the text I thank the participant for their participation, which we can do even if someone did not donate (they did participate).
