### ISSUE TITLE
After donating data 'done' button is spinning 

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#622]
**Describe the bug**
Already a known issue but just to document, when donating data, the donate button keeps spinning.
Some elements of the page (such as selecting and deleting items) are still working after donation.

**To Reproduce**
1. upload test data
2. donate the data 
3. click away the 'thank you message'
4. observe the behaviour

**Expected behavior**
- no spinner, application stays responsive
- maybe button becomes grayed out or shows 'done'
- rest of ux such as editing which data to share should no longer work. 

**Screenshots**
https://github.com/eyra/mono/assets/88683839/2eb78a3c-2c99-43a2-89fd-c54450f38222

**Desktop (please complete the following information):**
 - OS: macos
 - browser: any

**Comment by emielvdveen** [comment]
This is a feature and not a bug. Works in combination with Centerdata.
