### ISSUE TITLE
Scroll bars are visable in study CMS page

### ISSUE THREAD

**Issue by rowdyvl** [eyra/mono#626]
**Describe the bug**
Scroll bars are visable in study CMS page

**To Reproduce**
1. Go to https://next.dev.eyra.co/assignment/67/content or create a new data donation study
2. Bellow Settings and Tasklist, you will see a scroll bar
3. Also next to publish and preview button there is a vertical scroll bar

**Expected behavior**
Scroll bars should not be shown there since it has no use.

**Screenshots**
![image (44)](https://github.com/eyra/mono/assets/129153045/de760fe3-d734-4ac6-a709-7d9c672537ce)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows
 - Browser Chrome
 - Version latest

**Comment by TjerkNan** [comment]
- Getest op mac in chrome en safari, niet kunnen reproduceren
