### ISSUE TITLE
Blue bar around donation step in Firefox on MacOS

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#632]
**Describe the bug**
Blue bar around donation step in Firefox on MacOS, Safari doesn't have this issue.

**To Reproduce**
1. Start a donation flow
2. After uploading test data screen is presented to select / deselect data.
3. Observe blue line

**Expected behavior**
![Screenshot 2024-02-23 at 17 51 04](https://github.com/eyra/mono/assets/88683839/3ed60c5d-10a9-4171-af51-8e3b5cc03b6f)

**Screenshots**
![Screenshot 2024-02-23 at 17 48 10](https://github.com/eyra/mono/assets/88683839/889b45e0-d66d-429d-bbad-8eb3ab87001b)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox

**Comment by emielvdveen** [comment]
@TjerkNan which version of Firefox are you using? I could not reproduce on 122.0 and MacOS 13.5 (22G74)
<img width="1501" alt="Screenshot 2024-02-26 at 17 02 55" src="https://github.com/eyra/mono/assets/262448/69db6b1a-522c-4188-9072-3de0330f99cb">

**Comment by emielvdveen** [comment]
@TjerkNan sorry, I can reproduce it on next.dev.eyra.co

**Comment by TjerkNan** [comment]
Fixed in firefox on mac.
