### ISSUE TITLE
After donation, person can restart workflow, changing data?

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#633]
**Describe the bug**
After the 'thank you for your participation' screen, you can donate again. 

**To Reproduce**
1. Perform a data donation
2. observer that after the 'green' thanks for your participation message, you can donate again. 

**Expected behavior**
The donation buttons are greyed out or made inoperable or some solution with a similar outcome. 

**Screenshots**
https://github.com/eyra/mono/assets/88683839/1be07fde-dacb-4f2c-b6f8-90df3a3ace96

**Desktop (please complete the following information):**
 - OS: macos
 - Browser safari

**Comment by emielvdveen** [comment]
This is considered a feature. Data is always stored with a unique key so previous donated data is not overwritten.

**Comment by AdrienneMendrik** [comment]
Not going to be picked up.
