### ISSUE TITLE
Remove language switcher from Next

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#638]
- Taal button van Next te halen 
- Taal voor researchers altijd op engels te zetten 
- Taal van assignment kan in CMS voor de participant gezet worden op engels/duits/nederlands/..
- Taal kan niet meer gezet worden via de participant invite link
- Geen nederlandse vertalingen meer doervoeren anders dan in de assignment participanten flow gebruikt worden.

**Comment by TjerkNan** [comment]
- geobserveerd dat er geen staal keuze meer is
- getest met assigment dat juiste taal wordt getoond na instelling
