### ISSUE TITLE
Internal server error when creating a new benchmark project

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#651]
**Describe the bug**
Internal server error when creating a new benchmark project and clicking on the item.

**To Reproduce**
1. create new project
2. create new item of type Benchmark
3. Click on new item 
4. Observe that nothing happens for a while
5. Observe server error 500

**Expected behavior**
Not an Internal Server Error 500.

**Screenshots**
https://github.com/eyra/mono/assets/88683839/322920a8-4ba0-407c-893c-9623dc5040e3

**Desktop (please complete the following information):**
 - OS: macos
 - Browser safari

**Comment by emielvdveen** [comment]
Wil be fixed in Project Rank PreFer

**Comment by TjerkNan** [comment]
- This seems solved for me
