### ISSUE TITLE
Unable to change logo in Assignment CMS

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#652]
**Describe the bug**
Unable to change **Organisation logo** in Assignment CMS anymore after adding Language switch 

<img width="454" alt="Screenshot 2024-03-05 at 23 50 06" src="https://github.com/eyra/mono/assets/262448/37b945ef-daa2-4bb4-9802-5bb2a215f703">

**Comment by TjerkNan** [comment]
- login + assign logo
- logout
- Loigin observe new log
- change to other logo
- logout
- login and observe logo change
SUCCES
