### ISSUE TITLE
Internal Server Error 500 when accessing 'raw' Liss Panel participant url 

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#654]
**Describe the bug**
Internal Server Error 500 when accessing 'raw' Liss Panel participant url 

**To Reproduce**
1. Create data donation item
2. Use liss when configuring "Panel: section
3. Visit 'raw' (copy pasted) Liss URL without any parameters

**Expected behavior**
Benign error page

**Screenshots**
![Screenshot 2024-03-06 at 20 22 19](https://github.com/eyra/mono/assets/88683839/5ca60945-eb1c-4f67-8cbe-c487ae08e718)

**Desktop (please complete the following information):**
 - mac
 - safari

**Comment by AdrienneMendrik** [comment]
This will not be picked up
