### ISSUE TITLE
When visiting participant url of unpublished study a server error 503 is encountered

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#668]
**Describe the bug**
When visiting participant url of unpublished study a server error 503 is encountered

**To Reproduce**
1. create a data donation studiy
2. for panel select other and copy the participant url
3. finish the study settings, but don't publish
4. visit the copied url (change the {id} to a valid number)
5. observe the error

**Expected behavior**
A more friendly message that this study has been created but not yet published so researchers may know what's wrong.

**Screenshots**
![Screenshot 2024-03-20 at 22 07 21](https://github.com/eyra/mono/assets/88683839/013e5b2d-0551-4975-9681-96f80165f9ed)

**Desktop (please complete the following information):**
-macos safari

**Comment by AdrienneMendrik** [comment]
Will not be picked up right now, might reappear later.
