### ISSUE TITLE
Internal server error when clicking data donation item

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#674]
**Describe the bug**
Internal server error when clicking a data donation item.

**To Reproduce**
1. Go to an existing (old) data donation study (creating a new is going well)
2. Click on data donation item
4. See internal server error

**Expected behavior**
Enter the CMS of the data donation item. 

**Screenshots**
x

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser chrome
 - Version: next.dev.eyra.co

**Additional context**
Version after adding the benchmark assignment.

**Comment by TjerkNan** [comment]
- I tried to reproduce this with existing data donation studies but could not
