### ISSUE TITLE
No library in data donation item

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#675]
**Describe the bug**
When creating a new data donation item. There is no library in the workflow tab.

**To Reproduce**
1. Go to projects
2. Create new project
3. Add data donation item
4. Go to workflow tab
5. See workflow without library

**Expected behavior**
See a library to add tasks to the data donation workflow.

**Screenshots**
![Image](https://github.com/eyra/mono/assets/79082794/41083572-2292-40fa-8d75-034a398d1061)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version [Release #447 - Rank PreFer]

**Additional context**

**Comment by TjerkNan** [comment]
- I followed the instructions to the letter and can't reproduce the issue on Safari in a private window, I do see the library at the right side of the screen.
