### ISSUE TITLE
Invite user as participant on assignment

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#680]
A new optional tab in the Assignment CMS will be added. On that tab an URL will be available with a copy to clipboard button. This url can be used to send to selected users. 

Use case flow:

- Researcher copies url
- Researcher invites users using this url as a link
- User clicks on the link
- User logs in Next (if not already)
- Next adds user as participant to the assignment (if not already)
- User is forwarded to assignment participant flow

**Comment by TjerkNan** [comment]
- This process works for me
