### ISSUE TITLE
After downloading test data set, the "Done" button doesn't work anymore and participant can't continue

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#685]
**Describe the bug**
See title. 

Please note that I just uploaded a random zip file on my computer as "training data set"

**To Reproduce**
1. As a participant follow the flow and download the test dataset
2. press the blue "Done" button and observe no response

**Expected behavior**
Just that the flow continues

**Screenshots**
https://github.com/eyra/mono/assets/88683839/89e55e0b-8cb5-4ad4-99fe-70b58d59c40b

**Desktop (please complete the following information):**
macos + safari 
macos + Firefox 
macos + chrome

**Comment by emielvdveen** [comment]
@TjerkNan 

1. This is as expected. Please reupload the data set zip file in the CMS.
2. Can create an new issue for this finding?

**Comment by TjerkNan** [comment]
@emielvdveen https://github.com/eyra/mono/issues/695

**Comment by AdrienneMendrik** [comment]
Done
