### ISSUE TITLE
Very brief 'flicker' of plain text when clicking on Next logo during benchmark challenge assigment

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#687]
**Describe the bug**
Best to watch the video

**To Reproduce**
1. participate in a benchmark challenge as a participant
2. When the challenge / assignment starts, click on the next logo at the top left.
3. Observe a brief flickering of text

**Expected behavior**
No screen flickering

**Screenshots**

https://github.com/eyra/mono/assets/88683839/b29aefd9-ca18-4203-ab49-0b3c19b0ad45

**Desktop (please complete the following information):**
macos safari

**Comment by AdrienneMendrik** [comment]
This will not be picked up.
