### ISSUE TITLE
Check bigger when title shorter in task list

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#691]
**Describe the bug**
When the title of a task is shorter the check is bigger, then if the title is longer.

**To Reproduce**
1. Go to benchmark item
2. Use a short title for one task and a longer title for another
3. Click on preview
4. Go to task list
5. See error

**Expected behavior**
All checks to be the same size.

**Screenshots**
<img width="769" alt="Screenshot 2024-03-29 at 15 16 53" src="https://github.com/eyra/mono/assets/79082794/b6256eeb-05ba-404c-9561-83780b7d6c35">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome

**Comment by AdrienneMendrik** [comment]
Low prio, now just used a longer title to have them all look similar.

**Comment by emielvdveen** [comment]
@AdrienneMendrik We also need to look at the design to make more room for longer titels (apart from the check icon issue)

**Comment by emielvdveen** [comment]
Design suggestions from @Neo:

- More title padding (8-16px)
- Smaller font: 20px

**Comment by TjerkNan** [comment]
Gaat helaas nog steeds mis?

![image](https://github.com/eyra/mono/assets/88683839/1c8b70bb-254d-4049-ac75-56db6a5f901e)

![image](https://github.com/eyra/mono/assets/88683839/c9f0c151-e707-4fb8-8f7a-743c3397249a)

**Comment by TjerkNan** [comment]
ok
![image](https://github.com/eyra/mono/assets/88683839/ad878385-3d72-4ebd-b9d4-c25d9ccf734a)
