### ISSUE TITLE
Participant screen text is not contained on larger monitors

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#693]
**Describe the bug**

Text goes as wide as the entire window width. This is not great for reading text / readability imho.

**To Reproduce**
1. Visit:  https://next.dev.eyra.co/assignment/102/invite
2. login and observe the text fills the entire screen or page

**Expected behavior**
I believe text should be contained to a maximum width for readability and beyond a certain width, should not get wider.

**Screenshots**
![Screenshot 2024-03-30 at 12 34 31](https://github.com/eyra/mono/assets/88683839/16ed54de-3aa7-461a-afbc-430c9c1cd61e)

**Desktop (please complete the following information):**
macos safari

**Comment by AdrienneMendrik** [comment]
Not going to be picked up right now, might reappear later.
