### ISSUE TITLE
Downloading dataset results in redirect to about page

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#695]
**Describe the bug**

As a participant in the benchmark challenge, after clicking the download for the data set, an about page is shown in Firefox, and after that you are redirected back to the download data step, not completing it. I would expect to go to the 'submit method'.

**To Reproduce**
1. open the invite as a participant
2. follow the steps and click on the download zip 
3. observe the about page + being stuck in the download step

**Expected behavior**
No about page and just move to the 3rd submission step.

**Screenshots**

https://github.com/eyra/mono/assets/1312044/ab0fa661-8fcf-4c69-971a-e38fec2fae40

**Only an issue on macos firefox**

**Comment by TjerkNan** [comment]
@emielvdveen ik kan dit issue niet meer reproduceren op dev systeem.

**Comment by TjerkNan** [comment]
Niet goed getest, via de link van Adriënne https://next.dev.eyra.co/assignment/102/invite is het issue er gewoon. Via mijn studies niet.

**Comment by emielvdveen** [comment]
@TjerkNan heb je links naar jou stdies waarbij het wel werkt op Firefox?

**Comment by emielvdveen** [comment]
Ik heb probleem denk ik gevonden. Het 'download' attribuut zou alleen moeten werken als de url zelfde origin heeft als de website.

Zie Note bij: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#download
<img width="772" alt="Screenshot 2024-03-30 at 17 48 25" src="https://github.com/eyra/mono/assets/262448/725a9f9c-743f-420c-b44d-71e707249fc0">

Het lijkt erop dat Firefox hier op een andere manier (stricter?) mee om gaat dan de andere browsers. De download urls die wij gebruiken zijn urls die direct naar onze S3 verwijzen en niet naar https://next.eyra.co/..

Ik heb dit lokaal gereproduceerd op Firefox.

**Comment by TjerkNan** [comment]
https://next.dev.eyra.co/assignment/99/invite (gaat fout op firefox)
https://next.dev.eyra.co/assignment/103/invite (gaat fout op firefox)

**Comment by AdrienneMendrik** [comment]
Not going to be picked up, might come back later.
