### ISSUE TITLE
Add activity indicator to live file upload if file is large

### ISSUE THREAD

**Issue by mellelieuwes** [eyra/mono#696]
<img width="787" alt="Screenshot 2024-04-01 at 14 50 37" src="https://github.com/eyra/mono/assets/262448/15a6c929-5026-4760-a68b-d1fe2b9c56fb">

**Comment by TjerkNan** [comment]
@emielvdveen I encountered this issue myself where I was wondering if my upload was succesful or not during testing. Eventually a file showed up, but could confuse 'creators'.

**Comment by AdrienneMendrik** [comment]
@MelchiorKokernoot Zie figma: https://www.figma.com/design/UxitjYs2RK9cVsl2XS9jaQ?node-id=546-15716#991967547

**Comment by TjerkNan** [comment]
Works as intended.
