### ISSUE TITLE
Norton alert activation link

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#702]
**Describe the bug**

**To Reproduce**
1. Install Norton Safe Web extension in Chrome
2. Go to sign up page
3. Register
4. Got to activation email
5. Hover over the link with your mouse
6. See error

**Expected behavior**
No Norton Safe Web alert announcement.

**Screenshots**
<img width="634" alt="Screenshot 2024-04-02 at 14 25 10" src="https://github.com/eyra/mono/assets/79082794/45b4e172-7150-4988-8ec0-03323243d912">

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser chrome with Norton Safe Web extension 
<img width="413" alt="Screenshot 2024-04-02 at 14 26 21" src="https://github.com/eyra/mono/assets/79082794/953a8e32-0f66-4cd4-975a-226b747bbf73">

**Comment by emielvdveen** [comment]
@AdrienneMendrik can you report some details about the reason Norton thinks this link is suspicious?

**Comment by AdrienneMendrik** [comment]
Done
