### ISSUE TITLE
Open links in new tab

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#703]
When clicking in links in the about page, consent page, or helpdesk page it would be great if links open in a new tab, such that participants do not leave the Next platform.

**Comment by AdrienneMendrik** [comment]
@MelchiorKokernoot this is used in the following assignments:

Data donation: About page, Consent form, Helpdesk page
Benchmark challenge: About page, Consent form, Helpdesk page
Panl study (only on dev): About page, Consent form, Helpdesk page

But I think the About page, Consent form, Helpdesk page elements are all reusable modules. So changing one will also change the others, but good to check this.

**Comment by MelchiorKokernoot** [comment]
Quick search brengt me hier
https://github.com/basecamp/trix/issues/55

**Comment by TjerkNan** [comment]
Confirmed OK by creating links in all fields and clicking them, opens new tab.
