### ISSUE TITLE
User confirm url causes Internal Server Error 500

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#711]
**Describe the bug**
If you access this URL without any parameters, a server error is shown.

https://next.eyra.co/user/confirm

**To Reproduce**
1. Visit the URL
 
**Expected behavior**
A 'clean' user-friendly error message.

**Screenshots**
None

**Desktop (please complete the following information):**
Macos Safari

**Comment by AdrienneMendrik** [comment]
Will not be picked up right now, might reappear later.
