### ISSUE TITLE
Implement new submission task design

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#733]
![Desktop - Eyra Rank - Submission](https://github.com/eyra/mono/assets/262448/97648549-19f3-48d9-be11-5477258cd3f9)
![Desktop - Eyra Rank - closed](https://github.com/eyra/mono/assets/262448/edd13c63-4fb4-4354-b57b-178ff6364c55)

**Comment by AdrienneMendrik** [comment]
Done
