### ISSUE TITLE
Unconfigured deadline shows default text

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#734]
**Describe the bug**
If deadline is not configured for existing workflow placeholder <deadline?> is shown

**To Reproduce**
1. Do not touch existing study as researcher after new application deployment
2. Visit participant url as participant of existing study
3. At 'submit your results' step, observe message

**Expected behavior**
A text like 'there is no deadline configured at this moment.

**Screenshots**
![Screenshot 2024-04-15 at 20 36 39](https://github.com/eyra/mono/assets/88683839/1da22683-21d9-42e6-ad66-16a9d1cae65c)

**Desktop (please complete the following information):**
mac safari

**Comment by emielvdveen** [comment]
Context: having no deadline is not supported yet. But, it is not blocked to publish a challenge with submission task without a deadline. It is explicitly made ugly.

**Comment by emielvdveen** [comment]
@AdrienneMendrik willen we dit nu aanpakken?

**Comment by AdrienneMendrik** [comment]
@emielvdveen als het makkelijk is om op te pakken, maar het is geen blokker, want we zullen voor de PreFer challenge voor alle leaderboards deadlines zetten.

**Comment by AdrienneMendrik** [comment]
Fixed
