### ISSUE TITLE
Submission page does not show participant that deadline expired

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#735]
**Describe the bug**
When you keep the submission page open in your browser as a participant, nothing happens when the deadline expires. 
The application won't accept your submission but won't show an error either, when you press the submit button, just nothing happens.

You may decide that this is not a medium but a 'low prio' issue.

**To Reproduce**
1. Open the submission form as a participant
2. Keep the submission page open as the deadline expires
3. Click on submit (valid commit url) and observe nothing happens

**Expected behavior**
I expect the page to automatically update to the page that tells the user submissions are closed as soon as the deadline expires.

**Screenshots**
Spoel filmpje waar nodig even door.
https://github.com/eyra/mono/assets/88683839/3b4154e9-8843-4698-a4c7-d74794c947ee

**Desktop (please complete the following information):**
macos safari

**Comment by AdrienneMendrik** [comment]
Done
