### ISSUE TITLE
Benchmark participant sees clear message about deadline when logging on

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#736]
**Is your feature request related to a problem? Please describe.**
There is a risk that benchmark participants are not aware of the submission deadline and only find out when they try to submit.

**Describe the solution you'd like**
When logging on as a benchmark participant, I would expect that the deadline for the benchmark submission is displayed in my field of view at all times according to UX best practices. This assures that there is zero risk that people miss the deadline. 

Feel free to adjust the priority / assignees

**Comment by emielvdveen** [comment]
@TjerkNan  There is not 1 deadline but multiple deadlines, one for each submission task. The design for the submission task for participants has been changed with a better message about the deadline. See screenshot. Would this be sufficient in your eyes?

![Image](https://github.com/eyra/mono/assets/262448/eb02916b-6c2e-4000-8753-2c459321ab32)

**Comment by TjerkNan** [comment]
I was not aware of multiple deadlines but what you've done is an improvement. 

That said, it's about timing. I think the final submission deadline should already be shown somehow at the prepare method and download data stages (the earlier the better). Only if this makes sense to you from a benchmark workflow perspective. 

If a deadline is only known later on, so be it, no message should be shown on the prepare method and download pages. 
this example below is super ugly but it conveys the idea I had in my mind. It's similar to some kind of bar you might see on websites that anounce downtime/maintenance. 

![image](https://github.com/eyra/mono/assets/88683839/d328eb1a-73bd-48ad-b8ab-095f02899457)

**Comment by emielvdveen** [comment]
Good point. This requires more detailed design. I will assign this issue to @AdrienneMendrik to determine the priority.

**Comment by AdrienneMendrik** [comment]
Not going to be picked up, might come back in a different form later on if important.
