### ISSUE TITLE
%{deadline} instead of actual deadline date on submission page

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#738]
**Describe the bug**
It's as simple as the title says

**To Reproduce**
1. Visit participant url as participant
2. go to submission page
 
**Expected behavior**
The actual end-date shown

**Screenshots**

![Screenshot 2024-04-16 at 00 08 21](https://github.com/eyra/mono/assets/88683839/631d4fb0-74a1-4473-a82b-55cba73fe3e6)
![Screenshot 2024-04-16 at 00 08 10](https://github.com/eyra/mono/assets/88683839/4afe97a0-61fa-49aa-8270-d009b8629e8a)

**Desktop (please complete the following information):**
macos safari

**Comment by emielvdveen** [comment]
@AdrienneMendrik dit kan jij in de copy oplossen

**Comment by TjerkNan** [comment]
Opgelost
