### ISSUE TITLE
[Leaderboard] Exception while rendering preview

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#745]
<img width="442" alt="Screenshot 2024-04-19 at 11 07 31" src="https://github.com/eyra/mono/assets/262448/b758debd-3c40-4a73-9e54-881fd1984ee8">

**Comment by emielvdveen** [comment]
Due to not available metrics

**Comment by TjerkNan** [comment]
Empty benchmark freshly created, no data, just press preview and see no errors, no javascript console errors.?

**Comment by AdrienneMendrik** [comment]
Done
