### ISSUE TITLE
[Leaderboard] wrong spacing and font

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#747]
<img width="1524" alt="Screenshot 2024-04-19 at 11 06 36" src="https://github.com/eyra/mono/assets/262448/f49cffb8-b142-4733-8fee-662c8f5b7efd">

**Comment by TjerkNan** [comment]
Ziet er nu netjes uit 

![image](https://github.com/eyra/mono/assets/88683839/a76b4d4d-aafc-4954-a75a-dd82419f301a)
