### ISSUE TITLE
[Leaderboard] Tab label and content title do not match

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#748]
<img width="596" alt="Screenshot 2024-04-19 at 11 13 08" src="https://github.com/eyra/mono/assets/262448/3211649c-cad4-4a58-a5a2-376222dad529">

**Comment by emielvdveen** [comment]
<img width="987" alt="Screenshot 2024-04-19 at 12 06 45" src="https://github.com/eyra/mono/assets/262448/a18dd594-73d4-40b9-a6ec-199bd9f06b38">

**Comment by TjerkNan** [comment]
Settings, submissions, scores now match up
