### ISSUE TITLE
[Leaderboard] Default title should be title of submit task

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#750]
<img width="499" alt="Screenshot 2024-04-19 at 11 05 38" src="https://github.com/eyra/mono/assets/262448/d5b362b5-e0c9-48e9-bc04-f4951ca96e4f">

**Comment by TjerkNan** [comment]
Nieuwe submit task gemaakt met custom title en subtitle. Daarna leaderboard gemaakt en die had meteen de naam "Task Title"
![image](https://github.com/eyra/mono/assets/88683839/60efa97b-978a-4190-926c-024337eaed4f)
![image](https://github.com/eyra/mono/assets/88683839/247e1ff9-7743-407e-b03e-bb20d2b49235)
