### ISSUE TITLE
[Leaderboard] Missing the 3 blocks with meta information

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#753]
<img width="1838" alt="Screenshot 2024-04-19 at 11 20 41" src="https://github.com/eyra/mono/assets/262448/f924b186-0f9a-406b-8654-3d80820d38cf">

**Comment by emielvdveen** [comment]
This is the design:
<img width="1274" alt="Screenshot 2024-04-19 at 11 23 52" src="https://github.com/eyra/mono/assets/262448/a7142a1c-78b9-4cd5-bad4-7bfed17fc54e">

**Comment by TjerkNan** [comment]
Fixed
