### ISSUE TITLE
[Leaderboard] participants can only see themselves in anonymised variant

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#755]
Comment from dev: "er zit een hele basic 'anonymizer' in, op basis van de public / private flag in een leaderboard, dit mist nog de 'deelnemers kunnen wel zichzelf zien' optie."

**Comment by emielvdveen** [comment]
@TjerkNan Owners of a leaderboard always see the public variant of the leaderboard.

**Comment by TjerkNan** [comment]
Confirmed that when leaderboard is either public or private, owner can still see public data, not anonymous.
