### ISSUE TITLE
[Leaderboard] only owners and participants have access to private leaderboard

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#756]
Comment from dev "authentication voor het leaderboard: nog niet echt gelukt: ik check het in LeaderboardPage (zie L34), maar daar moet eigenlijk een redirect plaats vinden. Daar heb ik nog niets iets voor."

**Comment by TjerkNan** [comment]
- Heb account gemaakt dat geen invite heeft gehad
- Dit account krijg gewoon 403 te zien
- Accounts die wel een invite hebben gehad zien zowel private als public leaderboards.
