### ISSUE TITLE
[Leaderboard] Add number of submissions after title

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#759]
<img width="987" alt="Screenshot 2024-04-19 at 12 06 45" src="https://github.com/eyra/mono/assets/262448/06b0af63-f636-414a-8d5c-d86ba5d7e3ee">

**Comment by TjerkNan** [comment]
Correct
![image](https://github.com/eyra/mono/assets/88683839/a66245ec-4328-4003-ae3e-5a3296925cf6)
