### ISSUE TITLE
[Leaderboard] crash when processing scores csv

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#761]
<img width="2074" alt="Screenshot 2024-04-19 at 12 16 13" src="https://github.com/eyra/mono/assets/262448/696f1365-8571-47a2-9853-d02487cddf2b">

**Comment by TjerkNan** [comment]
@emielvdveen I think this one is solved but just want to check with you before closing.

**Comment by AdrienneMendrik** [comment]
Done
