### ISSUE TITLE
[Leaderboard] Gettext translations

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#763]
<img width="1518" alt="Screenshot 2024-04-19 at 14 14 17" src="https://github.com/eyra/mono/assets/262448/99aaff99-45f2-4856-a699-d15aec301939">

**Comment by emielvdveen** [comment]
<img width="1037" alt="Screenshot 2024-04-19 at 14 19 04" src="https://github.com/eyra/mono/assets/262448/0dd65cc5-d0de-4f7a-803e-8a8a539de0d2">

**Comment by AdrienneMendrik** [comment]
Done
