### ISSUE TITLE
[Leaderboard] auto-process scores (no processing button)

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#765]
<img width="1482" alt="Screenshot 2024-04-19 at 18 55 15" src="https://github.com/eyra/mono/assets/262448/5361280a-6fa6-4fbf-9556-001567b2ee5f">

**Comment by TjerkNan** [comment]
Confirmed 
![image](https://github.com/eyra/mono/assets/88683839/21529282-ceb8-41bd-835a-ec80ee7e6535)
