### ISSUE TITLE
[Leaderboard] Selecting a metric does not update the leaderboard

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#768]
**Describe the bug**
When clicking on p-value or length buttons, the table doesn't update, see video.
We should have seen 2 and 3 score values for length I think, based on your (Emiels) working example file.

Example leaderboard:
https://next.dev.eyra.co/graphite/leaderboard/7

**To Reproduce**
1. Upload data to leaderboard 
2. observe 

**Expected behavior**
That valid values are shown for the particular metric.

**Screenshots**
https://github.com/eyra/mono/assets/88683839/c4ba8c10-33d7-4136-b848-d54d4eda066b

**Desktop (please complete the following information):**
mac multiple browsers

**Comment by emielvdveen** [comment]
@TjerkNan duplicate of #762

**Comment by TjerkNan** [comment]
fixed gezien
