### ISSUE TITLE
[Leaderboard] Participant can access leaderboard settings 

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#769]
**Describe the bug**
A participant (authenticated account) can access the leaderboard settings if they know a specific url. 

**To Reproduce**
1. Have two accounts ready, one 'researcher' and one 'participant'.
2. Setup a benchmark study as the researcher
3. Have a participant register and use an invite sent by researcher
4. Participant fills out submission
5. Study is closed / deadline passes and leaderboard becomes available to participant 
6. participants modifies url (as discussed)

**Expected behavior**
The participant gets an access denied or is redirected to the actual leaderboard

**Screenshots**
Demo is shared through slack 

**Desktop (please complete the following information):**
N/A

**Comment by emielvdveen** [comment]
Fixed in https://github.com/eyra/mono/pull/710/commits/1898f4a4096d8c085373583cdd7379dc30de2c9b

**Comment by TjerkNan** [comment]
Could not reproduce, great!
