### ISSUE TITLE
[Leaderboard] changes not visible for participant

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#770]
**Describe the bug**
When a researcher changes the visibility of the leaderboard (public --> private) and vice versa, these changes aren't consistently processed and made visible on the actual leaderboard results view visible to participants. This not only true for public/private but also for text labels. 

A reliable way to assure changes are actually updated in the leaderboard is to:
1. Click projects
2. Click project
3. Click leaderboard card
4. Make change

You have to do this for every change you want to make. 

**To Reproduce**
1. Change leaderboard setting (public or private)
2. Observe that as a particpant watching the leaderboard nothing changes

**Expected behavior**
Leaderboards updates for participants as the change is made. 

**Screenshots**
https://github.com/eyra/mono/assets/88683839/cb54722b-7d83-4d6f-b155-6dc18900b21f

**Desktop (please complete the following information):**
mac safari firefox

**Comment by emielvdveen** [comment]
@TjerkNan FYI for te current leaderboard we will use only Private one. So switching is noy a blocking issue for upcoming release.

**Comment by TjerkNan** [comment]
Everything now changes real-time it is amazing
