### ISSUE TITLE
[Challenge] donations text should be changed in card

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#772]
<img width="485" alt="Screenshot 2024-04-22 at 11 15 24" src="https://github.com/eyra/mono/assets/262448/c32f402a-4ddb-4d3f-a43c-82fb367d2f95">

Donations is a term used in Data Donation template. Benchmark should have different text. I think we can even omit this since number of submissions is part of the Leaderboard Card. 

In the future Data Donations should potentially have en extra Storage Card with the number of donations on it. This way we can have an abstract Assignment card with only the number of participants on it or more information to the researcher about the Assignment. This Storage card could open a data browser kind of page to query/download all the data.

**Comment by emielvdveen** [comment]
![Image](https://github.com/eyra/mono/assets/262448/704f375b-5d2b-4e16-ba57-2130f55d0070)

Donation info is removed from card, also from Data Donation card

**Comment by TjerkNan** [comment]
Solved 
![image](https://github.com/eyra/mono/assets/88683839/4ce03de0-7e67-4be6-837d-cac902fe7386)
also validated with other study.
