### ISSUE TITLE
[Leaderboard] Status and error message not shown on dashboard

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#776]
The benchmark file output after running Jeroen's benchmark script contains the csv fields 'status' and 'error_message'. Those fields aren't shown and can't be parsed by the CSV importer as they aren't string representations of a float.

Showing the error could be informative for the end-user.

**Comment by emielvdveen** [comment]
@TjerkNan kan de file wel worden geparsed? of moet je de file handmatig aanpassen eerst?

**Comment by emielvdveen** [comment]
@TjerkNan kan je mij een voorbeeld file geven met error messages erin?

**Comment by TjerkNan** [comment]
Als je zelf in de leaderboard configuratie de status en error_message velden NIET opgeeft gaat de import prima omdat die velden genegeerd lijken te worden. De import lijkt alleen float values te accepteren voor kolommen. 

[graphite-9-results.csv](https://github.com/eyra/mono/files/15082732/graphite-9-results.csv)

**Comment by TjerkNan** [comment]
Solved 

![image](https://github.com/eyra/mono/assets/88683839/4e5312ac-cd3d-4d2b-9f4c-772b521145c6)
