### ISSUE TITLE
[Leaderboard] If file to be uploaded has been changed it can't be selected in dialog

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#778]
**Describe the bug**
This bug is a huge annoyance when testing.

When you edit a csv file to test the Leaderboard upload mechanism, you can't select the file.
You have to first close the file select dialog window and select again, after which it works.

**To Reproduce**
1. Edit csv file (just save it)
2. Try to select it in the file upload dialog box

**Expected behavior**
Always be able to select a file.

**Screenshots**
https://github.com/eyra/mono/assets/88683839/b715a465-0ed8-4a08-821c-ae5f223c64e4

**Desktop (please complete the following information):**
Macos + Safari + firefox

**Comment by emielvdveen** [comment]
Can not reproduce. Possibly Mac OS issue.
