### ISSUE TITLE
[Leaderboard] Bad request when accessing invalid url 

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#780]
**Describe the bug**
When accessing an invalid leaderboard id on the 'mangement page' (/leaderboard/{id}/content) with a non-integer value for id, we get a 'bad request' error. This may be benign and exactly correct, but maybe this should be double-checked.

**To Reproduce**
Create a test url like:
```
https://next.dev.eyra.co/graphite/leaderboard/7a/content
```

**Expected behavior**
If there's no underlying technical issue, error can stay. 

**Screenshots**
![Screenshot 2024-04-23 at 22 02 34](https://github.com/eyra/mono/assets/88683839/d80faf3c-a99f-4cda-869a-f8e7bbc52c20)

**Comment by emielvdveen** [comment]
@TjerkNan Technically this is correct. Parameters have the wrong format (string vs integer). Since this will only occur when someone is tampering with the url manually it is oke. Of the situation happend via a normal user pathway the error should be a better informed one.

I will close this issue.
