### ISSUE TITLE
[Leaderboard] Researcher has no way to visit leaderboard

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#782]
**Describe the bug**
After uploading the leaderboard data, there is an automatic redirect to the leaderboard. If the researcher navigates back to the leaderboard configuration screens, there is no way to view the leaderboard again. You must know the URL to view the leaderboard as a researcher.

**To Reproduce**
1. Create a leaderboard by uploading data
2. Observe the working leaderboard as a researcher
3. Navigate with the backbutton to the upload screen
4. Observe that nowhere in the app is there a way to view/visit the leaderboard again

**Expected behavior**
Some mechanism (link, button or otherwise) to view leaderboard as a researcher.

**Comment by emielvdveen** [comment]
@TjerkNan I will fix this by keeping the [Preview] button on the top right at all times.

**Comment by emielvdveen** [comment]
![Image](https://github.com/eyra/mono/assets/262448/c9a3209d-1708-460c-a752-c495ec8a9246)

**Comment by TjerkNan** [comment]
I've already used this, works perfectly.
