### ISSUE TITLE
[Leaderboard] Leaderboard is blank if metrics are not set

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#784]
**Describe the bug**
When metrics are not set, no leaderboard data is shown. At first this confused me. Now that I understand I would just want some kind of message/warning that informs me about this. 

~~I'm quite convinced that the leaderboard 9 shared below already contained test data from my side.~~
~~No matter my tests no data is shown. This is not true for all leaderboards as leaderboard 7 shows data just fine.~~

https://next.dev.eyra.co/graphite/leaderboard/9
https://next.dev.eyra.co/graphite/leaderboard/7

**To Reproduce**
1. Upload supplied test file
Notice there's still no data 

**Expected behavior**
~~Table with results. ~~ (warning) message informing me that no metrics are set

**Screenshots**
![image](https://github.com/eyra/mono/assets/88683839/59ee3426-2a11-4875-9c8b-8a715b4d3f41)

**Comment by TjerkNan** [comment]
[graphite-9-results.csv](https://github.com/eyra/mono/files/15099139/graphite-9-results.csv)

**Comment by AdrienneMendrik** [comment]
Not going to be picked up, might come back later in a different form.
