### ISSUE TITLE
[Leaderboard] Floats should have standard number of digits

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#786]
**Describe the bug**
Sometimes float values have just one number after the period instead of two, or way more. This looks less consistent.
Medium is maybe unfair but it's how I feel (my feeling is maybe unfair).

**To Reproduce**
See screenshot

**Expected behavior**
88.38
14.00
52.40

**Screenshots**
![Screenshot 2024-04-25 at 18 51 54](https://github.com/eyra/mono/assets/88683839/71e9b1af-f957-431f-869a-0e7124694571)
![Screenshot 2024-04-25 at 18 55 37](https://github.com/eyra/mono/assets/88683839/21aa3082-3ce3-4929-93c6-3b993d54fce3)

**Desktop (please complete the following information):**
mac safari

**Comment by emielvdveen** [comment]
@TjerkNan all the scores have now 2 digits as designed

**Comment by TjerkNan** [comment]
![image](https://github.com/eyra/mono/assets/88683839/1bc59ea4-2c26-4752-a9ed-60d9f01ce12f)
fixed
