### ISSUE TITLE
[Leaderboard] Generated on date format should be dd mm yyyy according to design 

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#787]
**Describe the bug**
According to the design shared in #752 the current date format yyyy-mm-dd should be dd-mm-yyyy

https://github.com/eyra/mono/issues/752#issuecomment-2066182696

**To Reproduce**
See screenshot

**Expected behavior**
dd-mm-yyyy

**Screenshots**
![image](https://github.com/eyra/mono/assets/88683839/cd3be179-ffa7-4cbe-8cf3-ecd52b68da2d)

**Desktop (please complete the following information):**
macos safari

**Comment by AdrienneMendrik** [comment]
Not going to be fixed.
