### ISSUE TITLE
[Leaderboard] leaderboard deadline does not reflect configured deadline

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#796]
**Describe the bug**
When the deadline is set for a particular submission task (to which the leaderboard is tied), changing the deadline at a later date does not result in a change of the deadline date in the leaderboard.

Maybe because it's user facing this medium or high. But it depends on context I guess.

**To Reproduce**
1. change the deadline date
2. observe that the leaderboard deadline date doesn't change no matter what you try

**Expected behavior**
I understood that the deadine on the leaderboard should be updated with the actual configured deadline for the submission task.

**Screenshots**
https://github.com/eyra/mono/assets/88683839/ee3f615a-3e05-4596-b3aa-4bfe11d09986

**Desktop (please complete the following information):**
Macos safari

**Comment by emielvdveen** [comment]
@TjerkNan the deadline translation is gone wrong. It should be "generated at".

**Comment by TjerkNan** [comment]
Clear I will create a new issue for that. this one is invalid then.
