### ISSUE TITLE
[Leaderboard] Leaderboard gets scrambled and empty when deadline is set too early

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#797]
**Describe the bug**
By configuring a deadline far in the past, the leaderboard gets 'scrambled'. This only happens if users are deliberately trying something that they should not do, so vey low prio.

**To Reproduce**
1. Make sure a leaderboard for a submission task exists 
2. Set the deadline for a submission task unreasonably far back, before the study started.
3. Observe the leaderboard 
 
**Expected behavior**
It should not be possible to select a deadline in the past beyond the start of the study or beyond whatever caused the screen to go haywire.

**Screenshots**
![Screenshot 2024-04-26 at 21 04 13](https://github.com/eyra/mono/assets/88683839/6672a599-9965-492a-ab9a-e086b66ac29f)

**Desktop (please complete the following information):**
macos safari

**Comment by emielvdveen** [comment]
@TjerkNan It must be possible to set the deadline as far back as the user wishes. I don't see a leaderboard that is gone haywire. I see a leaderboard that has its form not filled in.

**Comment by TjerkNan** [comment]
Clear I close the issue
