### ISSUE TITLE
[Leaderboard] leaderboard info block shows 'Deadline' instead of 'created on'

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#798]
**Describe the bug**
Wrong label for leaderboard creation date. 

P.S. I confirmed that when I upload new data the date indeed updates to the correct date.

**To Reproduce**
1. observe any leaderboard

**Expected behavior**
A text like "generated on / created on" 

**Screenshots**
![image](https://github.com/eyra/mono/assets/88683839/bf8447bc-a0b9-4246-bc02-247242776649)

**Desktop (please complete the following information):**
macos safari

**Comment by AdrienneMendrik** [comment]
Text shows generated on.
