### ISSUE TITLE
[Advertisement] project item card

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#802]
1. Click on card: forward user to CMS
2. Click on delete button: delete the project item and the advertisement + promotion
3. Click on duplicate button: makes a deep copy of project item => advertisement => promotion
4. Clink on edit button: shows a dialog to change the internal name of the advertisement

**Comment by TjerkNan** [comment]
#862 en #863 zijn denk ik aan deze gerelateerd

**Comment by emielvdveen** [comment]
Yes, so this issue can go to done singe the other two are more detailed
