### ISSUE TITLE
[Assignment] CMS create advertisement buttton

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#803]
In the Assignment CMS Participants tab needs a button to create an Advertisement. For the time being 1 Advertisement per Assignment will be supported. Therefor duplication of Advertisement on project level will not be available yet. 

When the advertisement is created,  a link "Go to Advertisement >" will be available. Advertisement can (for the time being)  only be deleted on project level.

**Comment by TjerkNan** [comment]
This works ok
