### ISSUE TITLE
[Assignment] implement questionnaire template

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#804]
1. Add templates to create project item dialog
2. Template will have single task workflow: alliance tool (questionnaire)

**Comment by TjerkNan** [comment]
@emielvdveen by default one qualtrics workflow is present, not sure about the alliance tool?

**Comment by emielvdveen** [comment]
Alliance tool is an abstract tool that does a clickout to an external online tool (eg: qualtrics). The questionnaire is a special variant of the alliance tool. It seems this issue can go to done.
