### ISSUE TITLE
[Home] Add section of citizen pools

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#820]
Home is the naked url (eg: next.eyra.co). The home will be personalized and localized. There will be version for:

- Visitors
- Creators
- Participants

And the region where the user resides will influence the content.

Add section of every citizen pool the user is participating in. Currently only `Panl`. The following version are build:

- Visitors: Panl section:  example studies
- Creators: Participations secion + Panl section:  available studies
- Participants: Participations secion + Panl section:  available studies

The home pages are not localized yet (all users see the Panl section). For localization see: #830

**Comment by TjerkNan** [comment]
One minor issue reported #865
