### ISSUE TITLE
[Account] Add verified concept

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#823]
1. Rename "researcher" flag to "creator" in user stable
2. Remove "student" flag from users table
3. Remove "coordinator" flag from users table
4. Add verified_at timestamp in users table

Users can be:
- Creator or participant (based on creator flag)
- Verified ✅ or Unverified❓ (based on verified_at timestamp)

Context:
- Only Verified ✅ Creators can publish on Next. Unverified❓Creators can only preview, nice for educational purposes. 
- Only Verified ✅ Creators can have licenses to software services (future, for the time being verified creators can use all services)
- Creator verification process (Know Your Customer) is not automated yet and is done outside of Next.
- Admins will be able to turn on the verification flag for a specific user (see #827)
- Participants will be able to change their account type to Unverified❓Creator in their profile (see #826). This will make the Projects menu item available for them.

**Comment by emielvdveen** [comment]
![Image](https://github.com/eyra/mono/assets/262448/f7c9973a-0223-42ee-bdf6-cd5c4c33ff6f)

**Comment by TjerkNan** [comment]
Created #866 for this but the feature itself is ok.
