### ISSUE TITLE
[Account] Participant + Creator signin/signup

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#824]
### Signup page can be rendered in two variants

1. Participant: /user/signup/participant
2. Creator: /user/signup/creator 

### Signin page has two options:

1. Signin as participant
2. Sign in as creator 

Each option has a **register** link to one of the available the signup page variants.

### Context
Creator is a technical term (iso researcher) for someone that has the **projects** menu item. The term creator probably need tos be translated into a more humanized copy for the UI. Examples:

- Professional
- Expert
- Academic
- Researcher (maybe this is still the best translation)

**Comment by TjerkNan** [comment]
I've tested with both the creator and participant roles and this feature works ok.
