### ISSUE TITLE
[Admin] Mark a User as Verified ✅

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#827]
A view must be made where admins can search for a user and turn on/off the verified flag.

**Comment by emielvdveen** [comment]
@AdrienneMendrik can you schedule this issue to an upcoming project?

**Comment by emielvdveen** [comment]
![Image](https://github.com/eyra/mono/assets/262448/f0e430c6-5cf9-4d99-8f8f-d5ee3ff50ec0)

**Comment by TjerkNan** [comment]
Works
