### ISSUE TITLE
My profile - edits not saved

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#836]
**Describe the bug**
When I go to my profile enter my name and then refresh, the info is gone. If I upload a picture, the profile image does not change.

**To Reproduce**
1. Go to 'My profile'
2. Enter Full name, display name or title
3. Refresh 
4. See empty field
5. Click select picture
6. Select picture
8. See error - no picture upload

**Expected behavior**
Text and image to be saved

**Screenshots**
Movie:
https://drive.google.com/file/d/102-AHyYsvmIWfS5yyK7YtPp30sUZmPQd/view?usp=drive_link

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser  chrome, safari

**Comment by TjerkNan** [comment]
Zie dit in log als ik het probeer:
```
core[18891]: {"time":"2024-06-06T20:51:17.215Z","severity":"info","message":"User 70 can_access? Elixir.Systems.Assignment.CrewPage: false","metadata":{"domain":["elixir"],"erl_level":"notice","remote_ip":"REDACTED","request_id":"F9Z-8AJ6W7hTsxMAA3QB"}}
Jun 06 20:51:24 ec2-web-dev-01 core[18891]: {"time":"2024-06-06T20:51:24.911Z","severity":"error","message":"GenServer #PID<0.16417.1> terminating\n** (FunctionClauseError) no function clause matching in Systems.Account.UserProfileForm.handle_event/3\n    (core 0.1.0) systems/account/user_profile_form.ex:71: Systems.Account.UserProfileForm.handle_event(\"save\", %{\"_target\" => [\"user_profile_edit_model\", \"fullname\"], \"user_profile_edit_model\" => %{\"displayname\" => \"\",  TRUNCATED
```

**Comment by TjerkNan** [comment]
Fixed aan mijn kant.

**Comment by AdrienneMendrik** [comment]
Fixed
