### ISSUE TITLE
Admin user search does not work on display name

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#850]
**Describe the bug**
I noticed that there is a test user with the display name 'Friet' but if you search this term you won't find this user.
The field 'Full name' is actually searchable as 'kaas' returns this account.

**To Reproduce**
1. Go to users tab as admin on dev env
2. Search for terms 'friet' and 'kaas' 

**Expected behavior**
Searching on 'friet' results in one account found.

**Screenshots**
![image](https://github.com/eyra/mono/assets/88683839/1cfa5f9d-892a-4824-bb9a-8c76e25cb65b)

**Desktop (please complete the following information):**
 - Chrome

**Comment by AdrienneMendrik** [comment]
Not now
