### ISSUE TITLE
Adding Internal server error 500 when adding workflow item

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#853]
**Describe the bug**
When adding tasks to a PANL Questionaire, adding the 'Onsite experiment' task results in a freeze and eventually an Internal Server Error. 

```
{"time":"2024-06-10T20:55:26.335Z","severity":"error","message":"#PID<0.2759.1> running CoreWeb.Endpoint (connection #PID<0.2758.1>, stream id 1) terminated\nServer: next.dev.eyra.co:80 (http)\nRequest: GET /assignment/136/content\n** (exit) an exception was raised:\n    ** (UndefinedFunctionError) function Systems.Lab.Form.__live__/0 is undefined (module Systems.Lab.Form is not available)\n        Systems.Lab.Form.__live__()\n        (phoenix_live_view 0.20.1) lib/phoenix_component.ex:1950: Phoenix.Component.live_component/1\n        (phoenix_live_view 0.20.1) lib/phoenix_live_view/tag_engine.ex:68: Phoenix.LiveView.TagEngine.component/3\n  
```
Maybe I'm testing something still under development?

**To Reproduce**
1. Create project
2. Add 'Panl questionnaire' item
3. Add Onsite Experiment' to workflow. 

**Expected behavior**
Task to be added to workflow. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Safari

**Comment by emielvdveen** [comment]
This is a "known" issue. Onsite Experiment experiment is not supported yet.
