### ISSUE TITLE
[Storage] project card

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#858]
Every project can have 1 Storage. Storages are created in Assignment CMS. New Assignments will automatically link use the Storage on the project if available.

The Storage card shows the following information:

- Fixed image specific for Storages
- Connection status
- Icon of the storage type (top right)
- Name (default: 'Internal storage' or 'Yoda')
- Nr of files currently stored

Click on the card will lead to Storage CMS #880

**Comment by TjerkNan** [comment]
* Fixed image specific for Storages

Storage has different image from item. 

* Connection status

Green 'connected' arrow visible.

* Icon of the storage type (top right)

TODO (issue encountered)

* Name (default: 'Internal storage' or 'Yoda')
* Nr of files currently stored

* Click on the card will lead to Storage CMS [#880](https://github.com/eyra/mono/issues/880)

**Comment by emielvdveen** [comment]
Everything seems to be correct. Issue can be moved to done

**Comment by TjerkNan** [comment]
I could not check that icon thing but it's ok, just a minor issue. We'll check wen yoda is done.
