### ISSUE TITLE
PDF Viewer width op brede schermen

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#861]
Max width = 1200px

**Comment by emielvdveen** [comment]
![Image](https://github.com/eyra/mono/assets/262448/ee162ad4-4fdc-43d2-a9e8-297b3fb223a6)

**Comment by TjerkNan** [comment]
De effectieve breedte van een LANDSCAPE PDF is nu zo'n 1000 pixels volgens mijn screenshots
