### ISSUE TITLE
New PANL studies are all 'example studies' 

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#865]
**Describe the bug**
According to [#820](https://github.com/eyra/mono/issues/820) unauthenticated visitors should only see the example studie. 

**To Reproduce**
1. observe frontpage as unauthenticated visitor (via private browser tab)

**Expected behavior**
New studies created by creator should not show up as example studies.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - Safari and firefox

**Comment by AdrienneMendrik** [comment]
This is how it should be, I'm still working on the copy, instead of example studies this will be: Available studies or something like this. We want to show which studies are available to draw people in.
