### ISSUE TITLE
When participant logson with google account, actual profile is that of creator

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#871]
**Describe the bug**
When I log in with a new google account to become a participant, I'm able to create projects, thus I have creator privileges.
When I log in with email/password I don't have these privileges.

**To Reproduce**
1. logon as participant with google account (not used)
2. Observe privileges

**Expected behavior**
To have participant privileges not creator privileges when logging on with google account.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - Safari

**Comment by TjerkNan** [comment]
@mellelieuwes when I login with one of my test participants acounts with both google and email I get full access like a researcher. If this is what we want, why do we have a login screen that is distinct from a participant and a  researcher, apart from the sign-in with surfconext?

**Comment by mellelieuwes** [comment]
@mellelieuwes did you create a completely new participant account before testing?

**Comment by TjerkNan** [comment]
> @mellelieuwes did you create a completely new participant account before testing?

No, I was assuming that this would be fixed for existing participant accounts, but a new account works as expected. Do you consider this issue closed because of this result?

**Comment by mellelieuwes** [comment]
@TjerkNan Access rights are appointed on account registration not login. Google and SURFconnext have an implicit registration step. First login is also a registration, so this might confuse things. We might need to create an explicit registration step for all auth platforms as well. 

The main reason for the participant/researcher login separation is to not confuse the users with options.

**Comment by mellelieuwes** [comment]
Participant accounts are only used in Benchmark Challenge on prod. It will be a thing for Panl when we launch that feature. For the existing Participants accounts on prod it is not a problem if they have creator rigths. So this issue can be closed.
