### ISSUE TITLE
Internal server error 500 when participating in study with creator account

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#876]
**Describe the bug**
I participate in a PANL questionaire as a creator. After the questionaire completes, I'm returned to the home page and I observe the internal server error. 

After this, the creator account is 'stuck' in this questionaire flow. When logging out and logging back in, error is still shown.

**To Reproduce**
1. participate in study on home page next dev
2. login as creator not as participant
3. click through questionaire and observe 'thank you'
4. continue and observe internal server error

**Expected behavior**

**Screenshots**

https://github.com/eyra/mono/assets/88683839/b26edd84-ce94-4016-89fa-792ac16af825

**Desktop (please complete the following information):**
 - safari

**Comment by mellelieuwes** [comment]
Seems to be fixed
