### ISSUE TITLE
Invite to unpublished study creates Internal Server Error 503

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#887]
**Describe the bug**
When I create an invite url assignment/154/invite and access this as a participant, an Internal Server Error 503 is shown if the study hasn't been published yet.

This is a rare issue that may never occur in practice.
**To Reproduce**
1. Create donation study
2. Press preview to generate link
3. Add /invite to the preview link 
4. Login in different browser as participant using this link
5. Observe error

**Expected behavior**
An access denied error.

**Screenshots**
![Screenshot 2024-06-26 at 23 06 56](https://github.com/eyra/mono/assets/88683839/5a7d3cd3-1ae5-4c48-bfc0-94b35a6e36b8)

**Desktop (please complete the following information):**
 - safari

**Comment by emielvdveen** [comment]
@TjerkNan this is by design. We don't have custom error pages yet.
