### ISSUE TITLE
[Storage] CMS: export all files

### ISSUE THREAD

**Issue by emielvdveen** [eyra/mono#892]
Export files is implemented using Packmatic: https://github.com/evadne/packmatic
This means we stream the zip file without using the filesystem or having the whole zip in memory. Every file is downloaded and streamed on the fly.

**Comment by emielvdveen** [comment]
@TjerkNan we need to test how the implementation is behaviing with a lot of files (1000+) and bytes (large files). To test the storage export the type of files does not matter. So for testing reason you can upload big files to test the user experience.

**Comment by TjerkNan** [comment]
I've created the script to generate files in S3 of various sizes and amounts so I think this particular card is solved.
