### ISSUE TITLE
Internal Server Error 500 when clicking on project after creating Yoda storage

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#895]
**Describe the bug**
I wanted to check how the storage cards look (eyra or yoda storage).
After creating a clean project and donation item, I created yoda storage.
Clicking on the storage link went fine and I saw the yoda configuration pane.
When I clicked on project and on the project with yoda storage, next freezes and eventually returns internal server error 500.

**To Reproduce**
1. create new project and data donation
2. create yoda storage 
3. click on project to the left
4. click on the project just created, observe nothing happens and wait for crash

**Expected behavior**
No crash and seeing the donation and storage cards

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Safari

**Comment by emielvdveen** [comment]
![Image](https://github.com/user-attachments/assets/95750eb0-f098-4a8f-9c43-a2014e9fcdf7)

**Comment by TjerkNan** [comment]
This particular issue is solved
