### ISSUE TITLE
Fix benchmark challenge language to English

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#896]
**Is your feature request related to a problem? Please describe.**
Benchmark challenges do not need to be translated into Dutch or German. English is sufficient.

**Describe the solution you'd like**
Benchmark challenges are fixed to English (na language setting required in CMS)

**Comment by emielvdveen** [comment]
Language can not be changed for Benchmark Challenges:
![Image](https://github.com/eyra/mono/assets/262448/a9d131d8-180a-4bf2-90d0-958f4e8215d3)

**Comment by TjerkNan** [comment]
@AdrienneMendrik confirmed that new benchmark study does not have a language setting.
