### ISSUE TITLE
Feature flag on Panl study for production release

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#897]
**Is your feature request related to a problem? Please describe.**
Add a feature flag to be able to remove Panl study from the project items, so that we can go to production without the Panl functionality.

**Describe the solution you'd like**
A feature flag to remove Panl study from project item options for a certain release.

**Comment by AdrienneMendrik** [comment]
Also feature flag for sign in through SURFconext:


![Image](https://github.com/eyra/mono/assets/79082794/b739a0ea-918f-4006-9702-be2a53953695)

**Comment by emielvdveen** [comment]
@TjerkNan two feature flags needs to set to disable panl and surf logic:

1. panl
2. surfconext_sign_in

Make sure both are not members of `ENABLED_APP_FEATURES` env variable.
