### ISSUE TITLE
About page not visible in preview, if already visited

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#903]
**Describe the bug**

**To Reproduce**
Steps:
- Create new data donation item
- Go to preview
- Click next at about page
- Go back to cms 
- Click preview again, preview immediately goes to consent page
- Not possible to view about page anymore

**Expected behavior**
About page is shown again so entire flow can be observed, including changes to the about page.

**Screenshots**

https://github.com/eyra/mono/assets/88683839/95332cf3-e643-4cc7-8786-3e077b190d79

**Desktop (please complete the following information):**
 - safari

**Comment by emielvdveen** [comment]
Two features are in conflict in the current implementation:

- Always show About page in preview mode
- Not show About page when returning from Qualtrics (Questionnaire)

Fixing this needs some structural refactoring (and testing).

**Comment by AdrienneMendrik** [comment]
@emielvdveen and @TjerkNan. Check, I understand. I think it would be best to change the copy in the CMS of the researcher for now to point them towards checking the information page when clicking the "i" at the bottom right in the preview flow. 

@emielvdveen and me discussed having an option in the future to preview per wysiwyg editor, this could solve the preview mode issues in a different way. But this is not for now.
