### ISSUE TITLE
Benchmark Challenge: Message after decline consent

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#907]
**Is your feature request related to a problem? Please describe.**
If I decline consent I do not see a message:

https://github.com/eyra/mono/assets/79082794/bf9d3a4c-301e-4b2e-b3f6-d3b0c80dc8db

**Describe the solution you'd like**
After declining consent I would like to see a message like with data donation:

![Image](https://github.com/eyra/mono/assets/79082794/c4e54e47-9506-41ee-b98d-e937d101fa41)

**Comment by TjerkNan** [comment]
Remarkable that you didn't crash the server with https://github.com/eyra/mono/issues/855 (consent no = server crash)

**Comment by MelchiorKokernoot** [comment]
@TjerkNan Hi it seems that this is no longer an issue, tested on dev and locally

**Comment by TjerkNan** [comment]
@MelchiorKokernoot this issue is indeed resolved, the screen is now present.
