### ISSUE TITLE
Internal Server Error 500 when clicking on Next logo in top left corner as a creator

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#915]
**Describe the bug**
I login as a creator/researcher. I click on the top left Next Logo and I get an ITS 500.
I've tested with two separate creator accounts.

If I do the same as a participant, I get no such error.

@emielvdveen if you revisit the home page while being logged on as a researcher, you'll immediately see an error 500 page.

**To Reproduce**
1. Login as researcher/contributor
2. Click on top left next logo

**Expected behavior**
No error, not sure what the right behaviour should be in this case.

**Screenshots**
https://github.com/eyra/mono/assets/88683839/a69820da-c464-4f65-ac9e-efeb6b9f9fd4

**Desktop (please complete the following information):**
 - Safari

**Comment by TjerkNan** [comment]
@emielvdveen last few times I tried and checked, this issue did not happen and I got a correct app message that informed me to close the window or something like that.

**Comment by TjerkNan** [comment]
Removed comment because it was wrong. Just to say the issue is gone when panl is disabled, but it was probably clear it's in the panl code.

**Comment by emielvdveen** [comment]
@TjerkNan can you verify this error on dev when Panl feature is enabled?

**Comment by TjerkNan** [comment]
@emielvdveen I can confirm that the issue is 'back' when panl is enabled.

**Comment by TjerkNan** [comment]
@emielvdveen  Unfortunately the issue persist for me. Let me know what you need. I don't see anything in the logs.

**Comment by emielvdveen** [comment]
@TjerkNan an internal 500 error must be visible in the logs. Can you hand me the error log?

**Comment by emielvdveen** [comment]
@TjerkNan I think this issue was not release on dev yet

**Comment by emielvdveen** [comment]
This release build includes a fix: https://github.com/eyra/mono/actions/runs/9980066932

**Comment by TjerkNan** [comment]
Solved
