### ISSUE TITLE
Storage card store requests does not reset after deleting all files

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#921]
**Describe the bug**
When cleaning all files (reset) the storage monitor card files and bytes is correctly reset to zero.
The 'store requests' value on the storage card is not reset. 

This is a judgement call as I can understand why this is not an issue. 

I would still recommend also resetting this store requests value because I would expect that when I reset storage, everything resets.

**To Reproduce**
1. Create a few donations
2. Observe counters increasing for store requests
3. delete all files
4. observe that store requests remains the same (not 0)

**Expected behavior**
Store requests is also reset to 0?

**Screenshots**
![image](https://github.com/eyra/mono/assets/88683839/49eb4ac3-7dda-4dd0-a90a-b0c0348fb43e)

**Desktop (please complete the following information):**
 - safari

**Comment by emielvdveen** [comment]
Ah forgot to change this as well. Will do it tomorrow.

**Comment by TjerkNan** [comment]
Is now solved
