### ISSUE TITLE
Projects can only be shared with people if you know their exact email address

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#924]
**Is your feature request related to a problem? Please describe.**
It should not be possible to share a project with people you don't know about. 

**Describe the solution you'd like**
If people want to share a project with somebody else, they should only be able to share it with somebody who:

1. Is registered on the platform as a researcher/creator (already true)
2. you know the exact email address for

**Comment by emielvdveen** [comment]
![Image](https://github.com/user-attachments/assets/40aae370-055f-46b3-bee8-0e6f2727fd1c)

**Comment by TjerkNan** [comment]
Confirmed this works
