### ISSUE TITLE
Publish a study is blocked in selfhosting

### ISSUE THREAD

**Issue by trbKnl** [eyra/mono#949]
**Describe the bug**
Reseacher is unable to publish a study is in self hosting variant.

**To Reproduce**
Steps to reproduce the behavior: when in a self hosting mode container build with BUNDLE=self

1. Go to workflow
2. Click on 'publish
3. See message: "Thank you for your interest. Publishing on Next platform is subject to payment"

**Expected behavior**
In self hosting a study is expected to be publishable.

**Comment by AdrienneMendrik** [comment]
Getting the message can be prevented by verifying a user, so they can publish.
