### ISSUE TITLE
Manually activate user account (Admin feature)

### ISSUE THREAD

**Issue by AdrienneMendrik** [eyra/mono#952]
**Is your feature request related to a problem? Please describe.**
It happens in some occasions that people who try to create a Next account do not receive the activation e-mail, and therefore cannot activate their user account. 

**Describe the solution you'd like**
Add a option in the admin screens on Next to activate an account manually (confirm in db), next to verify? In this way support staff can activate a user account when someone contacts support.

**Comment by TjerkNan** [comment]
Created new researcher account + new participant account + tested activation through feature (did not click link) and it works. Deactivation works.
