### ISSUE TITLE
Site layout is broken when pasting text with long lines

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#958]
**Describe the bug**
I've pasted some logs into a text field and noticed that the next app screen got wider than my monitor, due to the long lines. 
This means you can't access the publish and preview buttons anymore. You can recover by moving the window to the left, out of screen and eventually you get to the buttons.

**To Reproduce**
1. 

**Expected behavior**
- The site is always constrained within the limits of the browser window beyond a minimum resolution?
- A text field is always constrainted to the with of the element it resides in, may allow horizontal scrolling?

**Screenshots**
![Screenshot 2024-09-07 at 13 26 42](https://github.com/user-attachments/assets/4eb64b1a-d253-4e06-ae5e-01d3a690038b)
![Screenshot 2024-09-07 at 13 24 04](https://github.com/user-attachments/assets/fccdacbf-3e53-4ae5-b2e8-4df9b10eebd6)

**Thoughts**
- This is probably not PANL specific
- This is probably something in the site for longer

**Comment by AdrienneMendrik** [comment]
Not now
