### ISSUE TITLE
Not all existing accounts have a professional title field

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#960]
**Describe the bug**
See screenshots. Old accounts have this Professional Title  field, but new accounts don't.
Example accounts are in basecamp. For now it can be that 

**To Reproduce**
1. Login as account
2. Observe possible account settins

**Expected behavior**
All accounts have same fields

**Screens
![Screenshot 2024-09-07 at 15 04 38](https://github.com/user-attachments/assets/26202a02-e827-47cf-9e17-60c75ae41020)

![image](https://github.com/user-attachments/assets/e793e962-65cd-4e0a-b29a-2ca3de5a5f65)

**Comment by mellelieuwes** [comment]
@TjerkNan by design participants (non-creators) don't have a Professional Title in the Account. In Admin -> Users you can test this by making a participant a creator.

**Comment by TjerkNan** [comment]
Clear this is not an issue then.
