### ISSUE TITLE
Progress report

### ISSUE THREAD

**Issue by mellelieuwes** [eyra/mono#964]
To be able to have a more detailed overview of the progress per participant on a data donation study, we want to create a progress report functionality

Acceptance Criteria:

- There is an download "progress report" button below preview/ publish
- The format should be in excel see example: https://docs.google.com/spreadsheets/d/1PxJUFIV-o3v5wkwAHWh34Fyrws-iAboO3sZxPSTWpcA/edit?gid=0#gid=0
- Every task (workflow builder) should be represented in this overview including Consent
- See export progress report example for states per column

<img width="1459" alt="Screenshot 2024-09-25 at 11 29 04" src="https://github.com/user-attachments/assets/78747235-5e69-4461-b0a3-6da375d47c36">

Note: header "Participant ID" is changed to "Participant" in the latest implementation

**Comment by mellelieuwes** [comment]
@TjerkNan You can test this feature by clicking on [Progress report] in the Assignment Monitor tab.

![Image](https://github.com/user-attachments/assets/cf2be5c8-5c49-4542-87fb-964bf95a26f0)

**Comment by TjerkNan** [comment]
I've tested this feature and it works  - no issues found
