### ISSUE TITLE
Add snapchat to list of social media sites in donation workflow step

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#976]
**Is your feature request related to a problem? Please describe.**
Snapchat is not yet in the list of social media sites and a customer is going to run a study with Snapchat.

**Describe the solution you'd like**
Add snapchat to the list.

**Comment by mellelieuwes** [comment]
Fixed in release #542

**Comment by mellelieuwes** [comment]
Release [2024-10-15_542](https://github.com/eyra/mono/releases/tag/next_2024-10-15_542) deployed on dev
